name: ${{values.app_name}}-cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

      - name: Shorten commit id
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ '${{ secrets.DOCKERHUB_USERNAME }}' }}
          password: ${{ '${{ secrets.DOCKERHUB_TOKEN }}' }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: thanhlam2396/${{values.app_name}}:${{ '${{ env.COMMIT_ID }}' }}
    outputs:
      commit_id: ${{ '${{ env.COMMIT_ID }}' }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:

      - uses: actions/checkout@v3
      - name: Install yq
        uses: chrisdickinson/setup-yq@latest
      - name: Modify values file
        shell: bash
        run: |
          echo ${{ '${{needs.ci.outputs.commit_id}}' }}
          yq -Yi '.image.tag = "${{'${{needs.ci.outputs.commit_id}}' }}"' charts/${{values.app_name}}/values-${{values.app_env}}.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Updates values.yaml with commit ${{ '${{needs.ci.outputs.commit_id}}' }}'

      - name: Install argocd
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      - name: ArgoCD login
        uses: clowdhaus/argo-cd-action@main
        env:
          GITHUB_TOKEN: ${{ '${{ secrets.GITHUB_TOKEN }}' }}  # Escape đúng cách cho Backstage
        with:
          command: login
          options: argocd-server.argocd --insecure --grpc-web --username admin --password ${{ '${{ secrets.ARGOCD_PASSWORD }}' }}

      - name: Ensure argocd repo
        uses: clowdhaus/argo-cd-action@main
        with:
          command: repo add
          options: https://github.com/thanhlam2396-org/${{ values.app_name }}.git --upsert

      - name: Create or update ArgoCD app (idempotent)
        uses: clowdhaus/argo-cd-action@main
        with:
          command: app create
          options: ${{ values.app_name }} \
            --repo https://github.com/thanhlam2396-org/${{ values.app_name }}.git \
            --path charts/${{ values.app_name }} \
            --dest-namespace ${{ values.app_env }} \
            --dest-server https://kubernetes.default.svc \
            --values values-${{ values.app_env }}.yaml \
            --revision master \
            --sync-policy manual \
            --sync-option CreateNamespace=true \
            --upsert

      - name: Sync and wait
        uses: clowdhaus/argo-cd-action@main
        with:
          command: app sync
          options: ${{ values.app_name }} --wait --timeout 180
